### PR TITLE
Cloudapi v3

### PR DESCRIPTION
**Pull request by jasminSPC**

### CODE REVIEW

File: live_tests/test_lan_live.py [hunk 1]
```diff
@@ -132,10 +131,8 @@ def test_get_lan_members(self):
             lan_id=self.lan['id'])
 
         self.assertGreater(len(members), 0)
-        assertRegex(self, members['items'][0]['id'], self.resource['uuid_match'])
         self.assertEqual(members['items'][0]['type'], 'nic')
         self.assertEqual(members['items'][0]['properties']['name'], self.resource['nic']['name'])
-        assertRegex(self, members['items'][0]['properties']['mac'], self.resource['mac_match'])
```
Comment (jasminSPC) [inline live_tests/test_lan_live.py]: this import 
```
from six import assertRegex
```
was failing with this error message
```
'cannot import name assertRegex'
```

File: README.md [hunk 2]
```diff
@@ -120,7 +121,8 @@ Or if you want one with some volumes and NICs you would do:
         image='<IMAGE/SNAPSHOT-ID>',
         bus='VIRTIO'
         ssh_keys=['ssh-rsa AAAAB3NzaC1yc2EAAAADAQ...'],
-        image_password='s3cr3tpass0rd'
+        image_password='s3cr3tpass0rd',
+        availabilityZone='ZONE_3'
```
Comment (jasminSPC) [inline README.md]: Done

File: profitbricks/__init__.py [hunk 3]
```diff
@@ -1,5 +1,5 @@
 """ProfitBricks API Client Library for Python"""
 __version__ = '2.3.4'
```
Comment (jasminSPC) [inline profitbricks/__init__.py]: Done

File: live_tests/test_lan_live.py (hunk 1 above)
Comment (jasminSPC) [inline live_tests/test_lan_live.py]: Fixed it to work with both python 2.7 and 3.0 
Minimum requirement for `assertRegex` to function is six 1.10
I've added that change to `requirements.txt`

**Comment by jasminSPC** [comment]
Live test results 
```
root@96b836019a74:/profitbricks-sdk-python# python -m unittest discover tests 
...................................
----------------------------------------------------------------------
Ran 35 tests in 559.487s

OK
root@96b836019a74:/profitbricks-sdk-python# python -V
Python 3.5.2
```

```
root@5d7d5909914c:/profitbricks-sdk-python# python -m unittest discover tests 
...................................
----------------------------------------------------------------------
Ran 35 tests in 567.814s

OK
root@5d7d5909914c:/profitbricks-sdk-python# python -V
Python 2.7.12
```
